# jawaban nomor 1

In [1]:
import numpy as np

start = int(input("nilai awal: "))
end  = int(input("nilai akhir: "))

one_dimensional_array = np.arange(start, end+1)
two_dimensional_array = one_dimensional_array.reshape(2, -1)
three_dimensional_array = one_dimensional_array.reshape(2, 2, -1)

print("Array Satu Dimensi:")
print(one_dimensional_array)

print("Array Dua Dimensi:")
print(two_dimensional_array)

print("Array Tiga Dimensi:")
print(three_dimensional_array)



nilai awal: 1
nilai akhir: 28
Array Satu Dimensi:
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28]
Array Dua Dimensi:
[[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14]
 [15 16 17 18 19 20 21 22 23 24 25 26 27 28]]
Array Tiga Dimensi:
[[[ 1  2  3  4  5  6  7]
  [ 8  9 10 11 12 13 14]]

 [[15 16 17 18 19 20 21]
  [22 23 24 25 26 27 28]]]
