In [1]:
import numpy as np
import pandas as pd

import matplotlib.pyplot as plt
import seaborn as sns

import warnings
warnings.filterwarnings("ignore")

from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

In [2]:
iris = load_iris()

df = pd.DataFrame(data= np.c_[iris['data'], iris['target']],
                     columns= iris['feature_names'] + ['target'])

In [3]:
df

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                  5.1               3.5                1.4               0.2   
1                  4.9               3.0                1.4               0.2   
2                  4.7               3.2                1.3               0.2   
3                  4.6               3.1                1.5               0.2   
4                  5.0               3.6                1.4               0.2   
..                 ...               ...                ...               ...   
145                6.7               3.0                5.2               2.3   
146                6.3               2.5                5.0               1.9   
147                6.5               3.0                5.2               2.0   
148                6.2               3.4                5.4               2.3   
149                5.9               3.0                5.1               1.8   

     target  
0       0.0  
1       0.0  
2       0.0  
3       0.0  
4       0.0  
..      ...  
145     2.0  
146     2.0  
147     2.0  
148     2.0  
149     2.0  

[150 rows x 5 columns]

In [4]:
df['target'].value_counts() #cari unique value nya dari kolom target

0.0    50
1.0    50
2.0    50
Name: target, dtype: int64

In [5]:
X = df.drop(columns = 'target')   #bikin dua dataframe, yang satu tanpa kolom target, yang satu lagi cuma kolom target doang
y = df['target']

In [6]:
X

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                  5.1               3.5                1.4               0.2
1                  4.9               3.0                1.4               0.2
2                  4.7               3.2                1.3               0.2
3                  4.6               3.1                1.5               0.2
4                  5.0               3.6                1.4               0.2
..                 ...               ...                ...               ...
145                6.7               3.0                5.2               2.3
146                6.3               2.5                5.0               1.9
147                6.5               3.0                5.2               2.0
148                6.2               3.4                5.4               2.3
149                5.9               3.0                5.1               1.8

[150 rows x 4 columns]

In [7]:
y

0      0.0
1      0.0
2      0.0
3      0.0
4      0.0
      ... 
145    2.0
146    2.0
147    2.0
148    2.0
149    2.0
Name: target, Length: 150, dtype: float64

# Metode pertama, Logistic Regression.
This is just a rough example, there is still no separation of the training data, etc

In [10]:
logit = LogisticRegression()        #inisialisasi model
logit.fit(X,y)

logit.score(X,y)                    #untuk tau akurasi nya

0.9733333333333334

# Metode kedua, K-Nearest Neighbors (K-NN)

In [12]:
knn = KNeighborsClassifier()   #inisialisasi model

knn.fit(X,y)

knn.score(X,y)                 #untuk tau akurasi nya

0.9666666666666667

In [33]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25)
X_train

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
88                 5.6               3.0                4.1               1.3
95                 5.7               3.0                4.2               1.2
5                  5.4               3.9                1.7               0.4
20                 5.4               3.4                1.7               0.2
16                 5.4               3.9                1.3               0.4
..                 ...               ...                ...               ...
80                 5.5               2.4                3.8               1.1
104                6.5               3.0                5.8               2.2
2                  4.7               3.2                1.3               0.2
84                 5.4               3.0                4.5               1.5
133                6.3               2.8                5.1               1.5

[112 rows x 4 columns]

In [34]:
X_train.shape

(112, 4)

In [35]:
X_test.shape

(38, 4)

In [36]:
y_train.shape

(112,)

In [37]:
y_test.shape

(38,)

In [65]:
logit = LogisticRegression()
logit.fit(X_train, y_train) #proses training, pembentukan model

y_pred = logit.predict(X_test) #proses testing pake data testing nya, wich is X_test
accuracy_score(y_test, y_pred) #lalu dibandingin, data aktual sama data prediksi nya

0.9473684210526315

In [58]:
y_pred_proba = logit.predict_proba(X_test)
y_pred = logit.predict(X_test)

In [63]:
y_pred

array([2., 1., 0., 1., 1., 1., 0., 1., 1., 2., 2., 2., 2., 1., 0., 1., 1.,
       0., 1., 1., 2., 2., 1., 0., 0., 0., 0., 0., 2., 2., 2., 0., 1., 0.,
       0., 0., 2., 2.])

In [ ]:
y_pred_proba

array([[1.23897738e-04, 1.46395310e-01, 8.53480792e-01],
       [2.66040973e-04, 2.44898242e-01, 7.54835717e-01],
       [1.57767270e-05, 1.91772758e-02, 9.80806947e-01],
       [1.31579115e-03, 5.88247640e-01, 4.10436568e-01],
       [8.33392123e-04, 3.28312304e-01, 6.70854304e-01],
       [5.88930841e-03, 8.24040504e-01, 1.70070187e-01],
       [9.78565227e-01, 2.14347178e-02, 5.56169463e-08],
       [9.84306176e-01, 1.56937784e-02, 4.55081632e-08],
       [9.80960653e-01, 1.90392464e-02, 1.00224241e-07],
       [2.51668471e-03, 5.85991760e-01, 4.11491555e-01],
       [9.64697222e-02, 8.94666597e-01, 8.86368084e-03],
       [7.71245233e-03, 7.08658502e-01, 2.83629046e-01],
       [2.64557405e-02, 9.50261424e-01, 2.32828355e-02],
       [9.71038684e-01, 2.89612481e-02, 6.78671437e-08],
       [3.11200132e-02, 9.58551842e-01, 1.03281445e-02],
       [9.39156604e-01, 6.08432904e-02, 1.05582999e-07],
       [4.44951496e-02, 9.50933250e-01, 4.57160072e-03],
       [9.62559305e-01, 3.74405

In [ ]:
logit.intercept_

array([  9.41129704,   4.12504552, -13.53634256])

In [ ]:
X_train.columns

Index(['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)',
       'petal width (cm)'],
      dtype='object')

In [ ]:
logit.coef_

array([[-0.40806966,  0.84477209, -2.29001353, -0.98349916],
       [ 0.29663049, -0.6539209 , -0.16045689, -0.79353118],
       [ 0.11143916, -0.19085119,  2.45047043,  1.77703034]])

In [ ]:
knn = KNeighborsClassifier()
knn.fit(X_train, y_train)

y_pred = knn.predict(X_test)
accuracy_score(y_test, y_pred)

0.868421052631579

In [ ]:
y_pred

array([2., 2., 2., 1., 2., 1., 0., 0., 0., 2., 1., 1., 1., 0., 1., 0., 1.,
       0., 1., 0., 2., 1., 1., 2., 2., 0., 2., 1., 1., 0., 2., 1., 1., 1.,
       1., 1., 1., 2.])

In [ ]:
y_test

103    2.0
111    2.0
144    2.0
133    2.0
101    2.0
63     1.0
47     0.0
4      0.0
46     0.0
126    2.0
64     1.0
56     1.0
71     1.0
8      0.0
69     1.0
41     0.0
81     1.0
34     0.0
66     1.0
9      0.0
142    2.0
82     1.0
60     1.0
104    2.0
128    2.0
16     0.0
102    2.0
123    2.0
106    2.0
13     0.0
122    2.0
119    2.0
138    2.0
55     1.0
95     1.0
75     1.0
62     1.0
147    2.0
Name: target, dtype: float64